### PR TITLE
Update helper-rredlist.R

### PR DESCRIPTION
**Pull request by maelle**
I hope this will fail to prove my point.

### CODE REVIEW

**Comment by maelle** [comment]
The first commit failed :tada:, adding my workaround. :popcorn:

**Comment by maelle** [comment]
Yay!!

@sckott so in this case for recording cassettes one would need to coment out / not run the line setting the API key to foobar.

**Comment by maelle** [comment]
Things I need to define for a happy vcr workflow
* Steps to run before recording fixtures. (vcr setup)
* Steps to run after recording fixtures. (vcr teardown)
* Steps to run before running tests **when not recording** (not-vcr setup), in this case the setting of the API key to `foobar`.

**Comment by sckott** [comment]
thanks @maelle ! This is great. 

I wonder if a solution would have two parts:
- look for the env var required, in this case `IUCN_REDLIST_KEY`, and if not found, set some default like you did `IUCN_REDLIST_KEY = "foobar"`
- and only do the above thing if on a CI service && if cassettes already exist

thoughts?

**Comment by maelle** [comment]
Ah yes that sounds smarter

**Comment by maelle** [comment]
I tried something but have two doubts

* How do I correctly identify the fixtures folder, is the current code correct?

* Why only on CI and would I detect that the code is run on CI?

**Comment by maelle** [comment]
I don't have an API key set locally and tested the behaviors of tests (via `testthat::test_package()`)

* with the fixtures folder, they work.

* after renaming the fixtures folder, then the error message appears.

**Comment by sckott** [comment]
> How do I correctly identify the fixtures folder, is the current code correct?

A user can name that anything they like. But it should be in the `vcr_configure` call in the helper file. 

> Why only on CI and would I detect that the code is run on CI?

I don't quite follow the question.

**Comment by sckott** [comment]
> How do I correctly identify the fixtures folder, is the current code correct?

A user can name that anything they like. But it should be in the `vcr_configure` call in the helper file. 

> Why only on CI and would I detect that the code is run on CI?

I don't quite follow the question.

**Comment by sckott** [comment]
> How do I correctly identify the fixtures folder, is the current code correct?

A user can name that anything they like. But it should be in the `vcr_configure` call in the helper file. 

> Why only on CI and would I detect that the code is run on CI?

I don't quite follow the question.

**Comment by maelle** [comment]
I was asking about the last part of https://github.com/ropensci/rredlist/pull/41#issuecomment-582581836

**Comment by sckott** [comment]
Yeah, maybe that doesn't make sense to only do on CI. Then if the env var is not found tests can still run without failing locally, or on CRAN, or CI

**Comment by maelle** [comment]
Ok so is there anything I should edit in this PR?

**Comment by maelle** [comment]
Should CONTRIBUTING.md be updated?

**Comment by sckott** [comment]
yes, sounds good

**Pull request merged**
