### PR TITLE
Add in metadata function

### LINKED ISSUE #28: Metadata function
Would be extremely helpful if there was a searchable metadata file that gives all options of variables. These documents tend to be buried in the redlist API host website or in pdf format. For instance. For "threats" would be great to upload these documents as a reference table. 
[IUCN_threats-classification_2012.pdf](https://github.com/ropensci/rredlist/files/1921479/IUCN_threats-classification_2012.pdf)
[IUCN_dec_2012_guidance_on_threat_impact_scoring.pdf](https://github.com/ropensci/rredlist/files/1921480/IUCN_dec_2012_guidance_on_threat_impact_scoring.pdf)

### PR DESCRIPTION
**Pull request by arw36**
## Description
Added in a txt file (`metadata.txt`) with functions that warrant further documentation and hyperlinks this IUCN-hosted documentation. Added function `rl_metadata` to pull up this table (now requires `DT` package. I am a little unclear if hyperlinks work, or would require download user library? 

## Related Issue
fix #28

### CODE REVIEW

**Comment by sckott** [comment]
thanks @arw36 ! nice work!

Is that all the information that will be included moving forward? If that's all, we could more easily just include a manual file that has all the same information in a table, and not create a new function. Thoughts on that?

**Comment by arw36** [comment]
Totally fine with only having the manual file, or add the classification scheme to the references section of the help page for the four functions that currently have schemes (rl_growth_forms, rl_habitats, rl_threats, rl_measures).

**Comment by sckott** [comment]
thanks @arw36 for the changes! a few comments and request for change though:

Instead of editing the manual files directly, can you instead change the roxygen comments in each `.R` file? some documentation on that http://r-pkgs.had.co.nz/man.html#roxygen-comments 

Also, instead of adding a section in `R/rredlist-package.R` I was thinking you could make a new file, e .,g., `R/metadata.R` and then put in documentation only content, e.g. like 

```r
#' Metadata ....
#' 
#' @name rl_metadata
#' more text
#' ...
#' more text
NULL
```

then you could link to it with `[rl_metadata]` in other manual files

And in this file you could create lists and other elements, see the roxygen2 documentation https://cran.rstudio.com/web/packages/roxygen2/vignettes/markdown.html

**Comment by sckott** [comment]
@arw36 any interest in finishing this?

**Pull request closed without merging**
